### ISSUE TITLE
Null control character in the hash of breadcrumb

### ISSUE THREAD

**Issue by Rykee** [dlemmermann/PreferencesFX#64]
Hello!

I tried this little example: 

```
 PreferencesFx preferencesFx = PreferencesFx.of(MainApp.class,
                Category.of("Test", Group.of("TestGroup",
                        Setting.of("Test Setting", new SimpleStringProperty("aa")))));
 preferencesFx.show();
```

At the show() method I got an exception: 
```
Caused by: java.lang.IllegalArgumentException: Key contains code point U+0000
	at java.prefs/java.util.prefs.AbstractPreferences.get(AbstractPreferences.java:296)
	at com.dlsc.preferencesfx.util.StorageHandlerImpl.loadObject(StorageHandlerImpl.java:178)
	at com.dlsc.preferencesfx.model.Setting.loadSettingValue(Setting.java:359)
	at com.dlsc.preferencesfx.model.PreferencesFxModel.lambda$loadSettingValues$7(PreferencesFxModel.java:192)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1378)
	at com.dlsc.preferencesfx.model.PreferencesFxModel.loadSettingValues(PreferencesFxModel.java:189)
	at com.dlsc.preferencesfx.PreferencesFx.init(PreferencesFx.java:66)
	at com.dlsc.preferencesfx.PreferencesFx.<init>(PreferencesFx.java:61)
	at com.dlsc.preferencesfx.PreferencesFx.<init>(PreferencesFx.java:52)
	at com.dlsc.preferencesfx.PreferencesFx.of(PreferencesFx.java:97)
	at com.nokia.supervisor.controller.agent.MenuBarController.openSettings(MenuBarController.java:127)
```

The hashed breadcrumb contains a null control character which if prohibited in the key of a preference.
The breadcrumb: `Test#TestGroup#Test Setting` 
The hashed breadcrumb: ![image](https://user-images.githubusercontent.com/11543371/51900875-aa518500-23b6-11e9-97eb-ed359f335518.png) 
The null control character is at the index of 16. 

This prohibition for the preference key was added in JDK9 9 b63, see: 
https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8075156

Could you change the hashing algorithm so it avoids adding null control characters to the hashed value?

Cheers

Edit: Is this fixed in #55 ?

**Comment by martinfrancois** [comment]
Hi @Rykee, yes that's correct, it's fixed in #55. We will release a new version shortly.

**Comment by Rykee** [comment]
@martinfrancois Could you give an ETA on the release date?

**Comment by martinfrancois** [comment]
Hi @Rykee 
The fix for this issue was included in release `8.3.0` (for Java 8) and `11.3.0` (for Java 11), which has just been released.

**Comment by incendium** [comment]
I am running into this issue in `11.6.0`.  Under a fresh project, it still tries the invalid hash after it is unable to find an existing preference with the valid hash.

Stack trace:
```
Caused by: java.lang.IllegalArgumentException: Key contains code point U+0000
	at java.prefs/java.util.prefs.AbstractPreferences.get(AbstractPreferences.java:296)
	at com.dlsc.preferencesfx.util.PreferencesBasedStorageHandler.getSerializedPreferencesValue(PreferencesBasedStorageHandler.java:302)
	at com.dlsc.preferencesfx.util.PreferencesBasedStorageHandler.loadObject(PreferencesBasedStorageHandler.java:227)
	at com.dlsc.preferencesfx.model.Setting.loadSettingValue(Setting.java:517)
	at com.dlsc.preferencesfx.model.PreferencesFxModel.lambda$loadSettingValues$7(PreferencesFxModel.java:213)
	at com.dlsc.preferencesfx.model.PreferencesFxModel$$Lambda$199/0000000000000000.accept(Unknown Source)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at com.dlsc.preferencesfx.model.PreferencesFxModel.loadSettingValues(PreferencesFxModel.java:209)
	at com.dlsc.preferencesfx.PreferencesFx.init(PreferencesFx.java:69)
	at com.dlsc.preferencesfx.PreferencesFx.<init>(PreferencesFx.java:64)
	at com.dlsc.preferencesfx.PreferencesFx.<init>(PreferencesFx.java:55)
	at com.dlsc.preferencesfx.PreferencesFx.of(PreferencesFx.java:102)
```

**Comment by norbert-gaulia** [comment]
Is there any plans to merge this commit?  deprecatedHash() is total show stopper now

**Comment by fujohnwang** [comment]
11.6.0, still same problem

**Comment by martinfrancois** [comment]
@norbertas-gaulia @fujohnwang and @marvk can you please try 11.7.0 and report back if it works now?

**Comment by marvk** [comment]
@martinfrancois updated to 11.7.0 from 11.3.2 and my application is working fine, no perceivable difference so far! Looks good!
